spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: qwerty

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
